#include "ekf.hpp"

#include <stdexcept>
#include <algorithm>

namespace lunar {

// The filter. Both functions written by hand: the spec, the six equations and
// the four traps are in ekf.hpp, and the mathematics is typeset with charts in
// docs/ekf_formulas.pdf.
//
// docv_dsoc is deliberately NOT generated by tools/export_params.py, although
// ocv_v beside it is. The derivative is the measurement Jacobian — the heart
// of the filter — and porting it automatically would have answered the
// question the estimator exists to ask.
//
//   cmake --build estimator/build && ./estimator/build/test_ekf

double docv_dsoc(double soc) {
    const double x = 2.0 * soc - 1.0;
    double result = 0.0;
    for (int i = params::OCV_POLY_N - 1; i >= 1; --i){
         result = result * x + static_cast<double>(i) * params::OCV_POLY[i];
    }
    return result * static_cast<double>(params::CELLS_SERIES) * 2;
}


double Ekf::update(double current_a, double terminal_voltage_v, double dt_s) {
    
    soc_ = soc_ - params::COULOMBIC_EFFICIENCY * current_a * dt_s / (3600.0 * params::CAPACITY_AH);
    variance_ = variance_ + q_proc_;

    const double h_v_per_soc = docv_dsoc(soc_);
    const double predicted_voltage_v = params::ocv_v(soc_) - current_a * params::R_INTERNAL_OHM;
    const double residual_v = terminal_voltage_v - predicted_voltage_v;

    gain_ = variance_ * h_v_per_soc / (h_v_per_soc*h_v_per_soc * variance_ + r_meas_);
    soc_ = soc_ + gain_ * residual_v;
    variance_ = (1.0 - gain_ * h_v_per_soc) * variance_;
    
    soc_ = std::clamp(soc_, params::SOC_MIN, params::SOC_MAX);
    return soc_;

}

}  // namespace lunar
